# Standard 1 - Analytical approaches

_This standard relates to your ability to perform analysis using recognised techniques with an understanding of the context of the analysis. You should consider analytical projects or pieces of work where you have taken a business problem or question and translated this into an analytical task. This should demonstrate understanding of the question, choice of data with justification and limitations, appropriate presentation that addresses the question, understanding of what the data show and conclusions to be drawn given said limitations._

## SP1.1

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----|
SP1.1 Identify which tools and techniques are most appropriate for the situation and justify the measures used. These situations will sometimes be non-routine although precedents are likely to have been established before within the team. Demonstrates a critical understanding (including researching) of the organisation and health care environment. | What was the situation and analytical challenge? Which tools were available to complete the task? Which tool was selected and why? What were the benefits of using this particular tool? Where there any disadvantages? | empty | empty
 
## SP.2

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP1.2 Have knowledge of a range of statistical/ numerical techniques, procedures acquired through qualification to degree level or equivalent relevant experience | Identify statistical techniques being used. How did you get the knowledge of these techniques (formal learning, on-line resources, etc.)? | empty | empty

## SP.3

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP1.3 Be aware of the business questions that matter and how data fits with the organisation | How did you get a better understanding of the business requirements? Attendance at meetings, shadowing, etc. How is data used within your organisation and how do you fit it into this? | empty | empty

## SP.4

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP1.4 Understands the strengths and limitations to the data used (and not used) and addresses data quality issues, seeking clarification and advice and justifying choices. Limitations of data are clearly explained in outputs | What data was used (or excluded) from the analysis and why. How did you articulate any data quality issues? How did you ensure the data was interpreted correctly. | empty | empty

# Standard 2 – Critical Application

_This standard relates to your ability to select methods and apply these to analytical tasks.  This should include the process undertaken from developing an analytical question to providing an outcome._

## SP2.1

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.1 Analyses considers the range of facts or situations requiring analysis | What question prompted the analysis? What factors or situations could be impacting? How did you ensure your analysis was comprehensive and didn’t just look at a single factor? | empty | empty

## SP2.2

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.2 Dealing with statistical/analytical queries, assessing whether analyses are robust eg investigating data anomalies identified during analyses, instigating corrective action as required. | Did you encounter and problems during the analysis (e.g. data completeness, data quality issues etc.) and what did you do to address these? Did you deal with any questions or challenges as part of the task? | empty | empty

## SP2.3

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.3 Identifies potential issues and problems and escalates appropriately, and may recommend how these are addressed. | What methods of analysis did you consider and why did you select your chosen methodology? Did you seek advice/guidance on methodologies? Did you talk through your approach with a peer? | empty | empty

## SP2.4

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.4 Decides on the appropriate methods to be used for the analysis. Will seek advice on more complex analyses or new (to the analyst) methods / tools. May provide guidance to others on which methods are used. |	How did you decide on your analytical method? Did you seek peer support or review for more complex or new methods of analysis? Do you support other with analytical methods? | empty | empty

## SP2.5

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.5 Expected to work reliably without supervision and where appropriate may supervise others	Give examples of how you feel you work reliably without supervision. If you supervise others, how do you support them to work within a given framework? | SP2.6 Expected result is defined, but decides how this is best achieved.	What tools and methodologies did you use to perform the analysis and why? How did you arrive at the required output? | empty | empty

## SP2.7

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.7 Transform analytical insights into compelling business recommendations.	How did you progress the results of your analysis into recommendations for your organisation? Describe how you applied your analytical results to the business question and what recommendations you made. | How did you communicate these to the recipient of your analysis? | empty | empty

## SP2.8

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.8 Understandings (and communicates) strengths and limitations of data and appropriately addresses data quality issues | What data quality issues have you dealt with, how have you dealt with these and how did you ensure data was interpreted correctly based on any limitations? | empty | empty

## SP2.9

Standard | Commentary | Reflective Practice | Evidence Provided
|----|----|----|----| 
SP2.9 Understandings (and communicates) strengths and limitations of analytical approach, can justify why chosen and analysis as a whole and proposes alternative methods that could be employed to overcome limitations in future work | What analytical approaches did you consider and how did you select the one used? What were the strengths and limitations of the approaches? How did you communicate these to the recipient of your analysis? | empty | empty
